update
portalium/portalium-user pull request #5
Opened 2021-07-30 11:50 UTC by farukpinar

Updated bracket type selection.

2021-07-30 17:24 UTC, sinanbekar requested changes
Addition to all, ```&& $attribute != "seperator"``` should be removed.
https://github.com/farukpinar/portalium-user/blob/82fe5a6ca7fe4af2005e2bea72e81025e5c81d7e/src/controllers/backend/ImportController.php#L67

2021-07-30 17:24 UTC, sinanbekar commented on src/messages/tr-TR/user.php
> -    'The Signup Page feature must be activated in the Settings.' => 'Settings içerisinden Signup Page özelliğinin aktif edilmesi gerekiyor.'
.

2021-07-30 17:24 UTC, sinanbekar commented on src/views/backend/import/index.php
> +<?= $form->field($model, 'group')->dropDownList(\portalium\user\models\Group::getGroups(), ['prompt' => Module::t('Not Selected')]) ?>
```Group::getGroups()```

2021-12-04 12:49 UTC, diginova commented
Please update PR according to requesting changes.

2021-12-04 12:49 UTC, closed without merging